services:
  nginx:
      image: nginx:latest
      container_name: nginx
      restart: unless-stopped
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./cert/cert.pem:/etc/nginx/cert/cert.pem
        - ./cert/key.pem:/etc/nginx/cert/key.pem
      ports:
        - 443:443
      depends_on:
        - rest-api
      networks:
        - ecommers_network
  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4444:4444'
    networks:
      - ecommers_network

networks:
  ecommers_network:
    driver: bridge
