services:
  nginx:
      image: nginx:latest
      container_name: nginx
      restart: unless-stopped
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./cert/cert.pem:/etc/nginx/cert/cert.pem
        - ./cert/key.pem:/etc/nginx/cert/key.pem
      ports:
        - 443:443
      depends_on:
        - rest-api
#        - rest-api_02
#        - rest-api_03
      networks:
        - ecommerce_network

#  redis:
#    image: "redis"
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#
#    ports:
#      - "6379:6379"
#    networks:
#      - ecommerce_network
#    volumes:
#      - redis:/data

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - '4444:4444'
    networks:
      - ecommerce_network

#  rest-api_02:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./:/usr/src/app
#      - /usr/src/app/node_modules
#    restart: always
#    ports:
#      - '4445:4444'
#    networks:
#      - ecommerce_network

#  rest-api_03:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./:/usr/src/app
#      - /usr/src/app/node_modules
#    restart: always
#    ports:
#      - '4446:4444'
#    networks:
#      - ecommerce_network


networks:
  ecommerce_network:
    driver: bridge