services:
  nginx:
      image: nginx:latest
      container_name: nginx
      restart: unless-stopped
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./cert/cert.pem:/etc/nginx/cert/cert.pem
        - ./cert/key.pem:/etc/nginx/cert/key.pem
      ports:
        - 443:443
      depends_on:
        - rest-api
        - redis
      networks:
        - ecommerce_network

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - '4444:4444'
    depends_on:
      - redis
    networks:
      - ecommerce_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge