/product:
  # getAllProducts
  get:
    tags:
      - Product
    summary: 등록된 모든 제품 조회 - 관리자
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/product'
            examples:
              products:
                $ref: './openapi.yaml#/components/examples/getProducts'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

  # createProduct
  post:
    tags:
      - Product
    summary: 판매 제품 등록 - 판매자
    consumes:
      - application/json
    produces:
      - application/json
    requestBody:
      x-name: body
      required: true
      content:
        x-www-form-urlencoded:
          schema:
            $ref: './openapi.yaml#/components/schemas/product'
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/product'
            examples:
              productExample:
                $ref: './openapi.yaml#/components/examples/getProduct'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

  # deleteAllProducts
  delete:
    tags:
      - Product
    summary: 등록된 모든 제품 삭제 - 판매자
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/product'
            examples:
              deleteAllProducts:
                $ref: './openapi.yaml#/components/examples/deleteAllProducts'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

# getProduct
/product/{id}:
  get:
    tags:
      - Product
    summary: 제품의 상세 페이지 이동 - 모든 사용자
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/product'
            examples:
              product:
                $ref: './openapi.yaml#/components/examples/getProduct'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

  # updateProduct
  put:
    tags:
      - Product
    summary: 등록한 판매 제품 수정 - 판매자
    consumes:
      - application/json
    produces:
      - application/json
    requestBody:
      x-name: body
      required: true
      content:
        x-www-form-urlencoded:
          schema:
            $ref: './openapi.yaml#/components/schemas/product'
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/product'
            examples:
              product:
                $ref: './openapi.yaml#/components/examples/updateProduct'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

  delete:
    tags:
      - Product
    summary: 특정 제품 삭제 - 판매자
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/product'
            examples:
              deleteAllProducts:
                $ref: './openapi.yaml#/components/examples/deleteProduct'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'