/products:
  # getAllProducts
  get:
    tags:
      - Product
    summary: 등록된 모든 제품 조회 - 관리자
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/products'
            examples:
              products:
                $ref: './openapi.yaml#/components/examples/getAllProducts'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

  # createProduct
  post:
    tags:
      - Product
    summary: 판매 제품 등록 - 판매자
    consumes:
      - application/json
    produces:
      - application/json
    security:
      - $ref: './openapi.yaml#/components/securitySchemes/jwt'
    requestBody:
      x-name: body
      required: true
      content:
        x-www-form-urlencoded:
          schema:
            $ref: './openapi.yaml#/components/schemas/products'
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/products'
            examples:
              productExample:
                $ref: './openapi.yaml#/components/examples/getProduct'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

  # deleteAllProducts
  delete:
    tags:
      - Product
    summary: 등록된 모든 제품 삭제 - 판매자
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/products'
            examples:
              deleteAllProducts:
                $ref: './openapi.yaml#/components/examples/deleteAllProducts'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

/products/{id}:
  # getProduct
  get:
    tags:
      - Product
    summary: 제품의 상세 페이지 이동 - 모든 사용자
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - $ref: './openapi.yaml#/components/parameters/productId'
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/products'
            examples:
              product:
                $ref: './openapi.yaml#/components/examples/getProduct'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

  # updateProduct
  put:
    tags:
      - Product
    summary: 등록한 판매 제품 수정 - 판매자
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - $ref: './openapi.yaml#/components/parameters/productId'
    requestBody:
      x-name: body
      required: true
      content:
        x-www-form-urlencoded:
          schema:
            $ref: './openapi.yaml#/components/schemas/products'
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/products'
            examples:
              product:
                $ref: './openapi.yaml#/components/examples/updateProduct'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

  # deleteProduct
  delete:
    tags:
      - Product
    summary: 특정 제품 삭제 - 판매자
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - $ref: './openapi.yaml#/components/parameters/productId'
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/products'
            examples:
              deleteAllProducts:
                $ref: './openapi.yaml#/components/examples/deleteProduct'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'

  # createReplyToProduct
  post:
    tags:
      - Product
    summary: 후기 작성 - 모든 사용자
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - $ref: './openapi.yaml#/components/parameters/productId'
    requestBody:
      required: true
      content:
        x-www-form-urlencoded:
          schema:
            $ref: './openapi.yaml#/components/schemas/replies'
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: './openapi.yaml#/components/schemas/replies'
            examples:
              deleteAllProducts:
                $ref: './openapi.yaml#/components/examples/createReplyToProduct'
      '400':
        $ref: './openapi.yaml#/components/responses/BadRequest'
      '500':
        $ref: './openapi.yaml#/components/responses/InternalServerError'